# Generated by Django 3.2.11 on 2022-01-16 19:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import home.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CreateBy', models.CharField(max_length=127)),
                ('Task_name', models.CharField(max_length=127)),
                ('Zone', models.CharField(choices=[('Cockpit', 'Cockpit'), ('Cabin', 'Cabin'), ('Wing', 'Wing'), ('Landing Gear', 'Landing Gear'), ('Fuselage', 'Fuselage'), ('Engine', 'Engine'), ('Empennage', 'Empennage'), ('Avionic', 'Avionic')], default='Cockpit', max_length=127)),
                ('Task_Detail', models.TextField()),
                ('Assign', models.CharField(max_length=127)),
                ('DueDate', models.DateTimeField(blank=True, default=home.models.default_timenow, null=True)),
                ('Create_Date', models.DateTimeField(auto_now_add=True)),
                ('Update_Date', models.DateTimeField(blank=True, default=home.models.default_timenow)),
                ('Update_By', models.CharField(max_length=127)),
                ('Task_Performed', models.TextField()),
                ('Reviewed', models.BooleanField(blank=True, default=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(choices=[('0', 'Planner'), ('1', 'Mechanic')], default='1', max_length=127)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
